---
- name: Upgrade os packages

  hosts: upgrade

  serial: 1

  become: yes

  vars:

    upgrade_reboot_host_default: yes
    upgrade_reboot_timeout_default: 120

  roles:

    - nephelaiio.plugins

  tasks:

    - name: upgrade debian
      block:

        - name: upgrade apt
          apt:
            update_cache: yes
            force_apt_get: yes
            upgrade: safe

        - name: remove apt orphans
          command: apt autoremove -y
          changed_when: false
          when: (upgrade_remove_orphans | default('no')) | bool

      when: ansible_os_family == 'Debian'

    - name: upgrade redhat
      block:

        - name: upgrade yum
          yum:
            name: '*'
            state: latest
            update_only: yes
            update_cache: yes
          tags:
            - skip_ansible_lint

      when: ansible_os_family == 'RedHat'

    - name: upgrade arch
      block:

        - name: upgrade pacman
          pacman:
            update_cache: yes
            upgrade: yes

        - name: find pacman orphans
          changed_when: false
          failed_when: false
          command: pacman -Qtdq
          register: orphans

        - name: remove pacman orphans
          command: pacman -Rns --noconfirm {{ orphans.stdout }}
          when:
            - orphans.stdout != ''
            - (upgrade_remove_orphans | default('no')) | bool

      when: ansible_os_family == 'Archlinux'

    - block:

        - name: install yum utils
          package:
            name: yum-utils
            state: latest

        - name: check reboot status
          command: needs-restarting -r
          register: reboot_query
          failed_when: false
          changed_when: false

        - name: reboot host
          reboot:
            reboot_timeout: "{{ reboot_timeout | default(upgrade_reboot_timeout_default) }}"
          when: reboot_query.rc == 1

      when:
        - ansible_os_family == 'RedHat'
        - upgrade_reboot_host | default(upgrade_reboot_host_default) | bool

    - block:

        - name: check reboot status
          stat:
            path: /var/run/reboot-required
          register: reboot_query
          changed_when: false

        - name: reboot host
          reboot:
            reboot_timeout: "{{ upgrade_reboot_timeout | default(upgrade_reboot_timeout_default) }}"
          when: reboot_query.stat.exists

      when:
        - ansible_os_family == 'Debian'
        - upgrade_reboot_host | default(upgrade_reboot_host_default) | bool
