---
- name: retrieve organization id - {{ project.name }}
  command: "awx-cli organization get -n \"{{ organization.name }}\" -f json"
  changed_when: false
  register: org_id

- name: build project configuration options - {{ project.name }}
  set_fact:
    project_name: "-n {{ project.name | string | quote }}"
    project_description: "{{ ('--description ' + project.description | string | quote) if 'description' in project else '' }}"
    project_scm_type: "--scm-type {{ project.scm_type | string | quote }}"
    project_scm_url: "{{ ('--scm-url ' + project.scm_url | string | quote) if 'scm_url' in project else '' }}"
    project_scm_branch: "{{ ('--scm-branch ' + project.scm_branch | string | quote) if 'scm_branch' in project else '' }}"
    project_scm_credential: "{{ ('--scm-credential ' + project.scm_credential | string | quote) if 'scm_credential' in project else '' }}"
    project_scm_clean: "{{ ('--scm-clean ' + project.scm_clean | string | quote) if 'scm_clean' in project else '' }}"
    project_scm_delete_on_update: "{{ ('--scm-delete-on-update ' + project.scm_delete_on_update | string | quote) if 'scm_delete_on_update' in project else '' }}"
    project_scm_update_on_launch: "{{ ('--scm-update-on-launch ' + project.scm_update_on_launch | string | quote) if 'scm_update_on_launch' in project else '' }}"
    project_scm_update_cache_timeout: "{{ ('--scm-update-cache-timeout ' + project.scm_update_cache_timeout | string | quote) if 'scm_update_cache_timeout' in project else '' }}"
    project_job_timeout: "{{ ('--job-timeout ' + (project.job_timeout | string | quote) ) if 'job_timeout' in project else '' }}"

- name: build project creation command - {{ project.name }}
  set_fact:
    project_source_create_args: "{{ project_name }} {{ project_description }} {{ project_scm_type }} {{ project_scm_url }} {{ project_scm_branch }} {{ project_scm_credential }} {{ project_scm_clean }} {{ project_scm_delete_on_update }} {{ project_scm_update_on_launch }} {{ project_job_timeout }}"

- name: create project - {{ project.name }}
  command: "awx-cli project create --monitor --organization {{ organization.name }} {{ project_scm_update_cache_timeout }} {{ project_source_create_args }} --force-on-exists"
  changed_when: false

- name: update project - {{ project.name }}
  command: "awx-cli project update {{ project_name }}"
